name: Playwright Tests
on: 
    push:
        branches: [ main ]
jobs:
    playwrighttests:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.45.2-focal
            env:
                ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Run Tests
              run: |
                echo "Start the shopping store application"
                chmod +x ./shopping-store-linux-amd64 &
                echo "Install dependencies from lockfile"
                npm ci
                echo "Run playwright tests"
                npm run test:ci